use_frameworks!

platform :ios, '9.0'

target 'xxssss_Example' do
#  pod 'xxssss', :path => '../'
  pod 'Cartography', '~> 3.0'
  pod 'AsyncSwift'
  # pod 'SwiftColor'
  pod 'Appirater'
  pod 'MBProgressHUD'
  pod 'ICDMaterialActivityIndicatorView', '~> 0.1.0'
  # pod 'ICSPullToRefresh', '~> 0.6'
  pod 'ISO8601DateFormatter', '~> 0.8'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'CocoaLumberjack/Swift', '~> 3.4.1'
  # pod 'PSOperations', '~> 4.0.1'
  pod 'LogglyLogger-CocoaLumberjack', '~> 3.0.0'
  pod 'RealmSwift', '~> 2.10.2'
  pod 'KeychainAccess', '~> 3.1.1'
  
 end
